version: '3.8'

services:
  broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    networks:
      - dognet

  frame1:
    build: ./frame-app
    environment:
      - MQTT_DISCOVERY=1
    networks:
      - dognet

  frame2:
    build: ./frame-app
    environment:
      - MQTT_DISCOVERY=1
    networks:
      - dognet

networks:
  dognet:
    driver: bridge
